import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import Groq from 'groq-sdk';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.join(__dirname, '.env') });

const app = express();
app.use(cors());
app.use(express.json());

const port = process.env.PORT || 3001;

// Initialize Groq SDK
const groq = new Groq({
  apiKey: process.env.GROQ_API_KEY
});

app.post('/api/generate', async (req, res) => {
  try {
    const { content, platforms, tone } = req.body;
    
    if (!content) {
      return res.status(400).json({ error: 'Content is required.' });
    }

    const platformList = platforms && platforms.length > 0 ? platforms.join(', ') : 'X, LinkedIn, Reddit, Instagram, Facebook';
    const selectedTone = tone || 'Professional';

    const systemPrompt = `You are an expert social media copywriter. 
The user will provide a topic or draft content.
Your task is to generate optimized social media posts for the following platforms: ${platformList}.
The tone should be: ${selectedTone}.
For each platform, generate a highly engaging post formatted specifically for that platform's audience and constraints.
Also, generate a few extra useful snippets: 'Thread Version' (for X), 'Reel Hook' (for Instagram/TikTok), '30-Second Reel Script', and 'Hashtags'.

Return the result as a valid JSON object matching this exact schema, where each value is an array of 3 variant strings for the user to choose from:
{
  "X Post": ["variant1", "variant2", "variant3"],
  "LinkedIn Post": ["variant1", "variant2", "variant3"],
  "Reddit Post": ["variant1", "variant2", "variant3"],
  "Instagram Caption": ["variant1", "variant2", "variant3"],
  "Facebook Post": ["variant1", "variant2", "variant3"],
  "Thread Version": ["variant1", "variant2", "variant3"],
  "Reel Hook": ["variant1", "variant2", "variant3"],
  "30-Second Reel Script": ["variant1", "variant2", "variant3"],
  "Hashtags": ["variant1", "variant2", "variant3"]
}

Return ONLY valid JSON. Do not include markdown formatting like \`\`\`json.`;

    const chatCompletion = await groq.chat.completions.create({
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: `Content/Topic:\n${content}` }
      ],
      model: 'llama-3.3-70b-versatile',
      temperature: 0.7,
      response_format: { type: 'json_object' }
    });

    const responseText = chatCompletion.choices[0]?.message?.content || '{}';

    let jsonResult;
    try {
        jsonResult = JSON.parse(responseText);
    } catch (parseError) {
        console.error("Failed to parse Groq response as JSON:", responseText);
        return res.status(500).json({ error: 'AI returned invalid JSON format.' });
    }

    res.json(jsonResult);
  } catch (error) {
    console.error('Error generating content:', error);
    res.status(500).json({ error: 'Failed to generate content.' });
  }
});

// Serve static files from the React app (the 'dist' folder generated by Vite)
app.use(express.static(path.join(__dirname, '../dist')));

// The "catchall" handler: for any request that doesn't match one above, send back React's index.html file.
app.use((req, res, next) => {
  if (req.method === 'GET' && !req.path.startsWith('/api')) {
    res.sendFile(path.join(__dirname, '../dist/index.html'));
  } else {
    next();
  }
});

app.listen(port, () => {
  console.log(`Server listening at http://localhost:${port}`);
});
